### ISSUE TITLE
AttributeError: module 'pexpect' has no attribute 'spawn'

### ISSUE THREAD

**Issue by R0XFOR** [fluzzi/connpy#1]
When I running the script, such an error occurs. Help me please.

```py
import connpy

class Telnet:
    def auth(name:str, host:str, user:str, password:str):
        router = connpy.node(name, host, user = user, password = password)
        router.run("ls")
        print(router.output)
        router.run("exit")


if __name__ == "__main__":
    session = Telnet.auth("router", "192.168.100.1", "root", "Zte521")
```

```
Traceback (most recent call last):
  File "c:\Users\andre\Documents\MyProjects\Python\telnet\main.py", line 12, in <module>
    session = Telnet.auth("router", "192.168.100.1", "root", "Zte521")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\andre\Documents\MyProjects\Python\telnet\main.py", line 6, in auth
    router.run("ls")
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\connpy\core.py", line 251, in run     
    connect = self._connect(timeout = timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\connpy\core.py", line 414, in _connect
    child = pexpect.spawn(cmd)
            ^^^^^^^^^^^^^
AttributeError: module 'pexpect' has no attribute 'spawn'
```

**Comment by fluzzi** [comment]
Are you using windows? This only run in Linux or macos
